name: shared
description: Shared app package.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.0.0
  crypto: ^3.0.1
  data_providers:
    path: ../data_providers
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  provider: ^5.0.0
  rxdart: ^0.27.1

dev_dependencies:
  pedantic: ^1.11.1
  very_good_analysis: ^2.3.0
