name: user_repository
description: User repository.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  data_providers:
    path: ../data_providers
  flutter:
    sdk: flutter
  shared:
    path: ../shared

dev_dependencies:
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  very_good_analysis: ^2.3.0
