name: quizapp
description: QuizApp Built with Flutter & Firebase.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  assets_repository:
    path: packages/assets_repository
  data_providers:
    path: packages/data_providers
  equatable: ^2.0.3
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  quizzes_repository:
    path: packages/quizzes_repository
  shared:
    path: packages/shared
  topics_repository:
    path: packages/topics_repository
  transparent_image: ^2.0.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.1.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/covers/
    - assets/congrats.gif
