name: quizapp
description: QuizApp Built with Flutter & Firebase.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  data_sources:
    path: packages/data_sources
  shared:
    path: packages/shared
  user_repository:
    path: packages/user_repository
  equatable: ^2.0.3
  flow_builder: ^0.0.3
  flutter_bloc: ^7.0.1
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.1.2

flutter:
  uses-material-design: true
  generate: true
